//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atelier5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int Order_ID { get; set; }
        public int Product_ID { get; set; }
        public decimal Unit_Price { get; set; }
        public short Quantity { get; set; }
        public float Discount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
